import {
    HOST_REGISTER,
    PORT_REGISTER_DISCOVERY,
    PORT_REGISTER_INFOSEC,
    PORT_REGISTER_STATUS,
    URL_REGISTER_DATA_HOLDER_BRANDS_SUMMARY,
    URL_REGISTER_DATA_HOLDER_BRANDS_STATUSES,
    URL_REGISTER_DATA_RECIPIENTS_STATUSES,
    URL_REGISTER_SOFTWARE_PRODUCTS_STATUSES,
    URL_REGISTER_DATA_HOLDER_BRANDS,
    URL_REGISTER_DATA_RECIPIENTS,
    URL_REGISTER_JWKS
} from './input-parameters.js';


// Register Base Urls
const BASE_URL_REGISTER_DATA = HOST_REGISTER + ':' + PORT_REGISTER_STATUS;
const BASE_URL_REGISTER_DISCOVERY = HOST_REGISTER + ':' + PORT_REGISTER_DISCOVERY;

// Register Endpoints (No Auth)
export const registerEndpointsNoAuth = {
    
    // Data Endpoints
    DATA_HOLDER_BRANDS_SUMMARY: BASE_URL_REGISTER_DATA + URL_REGISTER_DATA_HOLDER_BRANDS_SUMMARY,
    DATA_HOLDER_BRANDS_STATUSES: BASE_URL_REGISTER_DATA + URL_REGISTER_DATA_HOLDER_BRANDS_STATUSES,
    DATA_RECIPIENTS_STATUSES: BASE_URL_REGISTER_DATA + URL_REGISTER_DATA_RECIPIENTS_STATUSES,
    SOFTWARE_PRODUCTS_STATUSES: BASE_URL_REGISTER_DATA + URL_REGISTER_SOFTWARE_PRODUCTS_STATUSES,
    
    // Discovery Endpoints
    DATA_RECIPIENTS: BASE_URL_REGISTER_DISCOVERY + URL_REGISTER_DATA_RECIPIENTS,

    // Infosec Endpoints
    JWKS: HOST_REGISTER + ':' + PORT_REGISTER_INFOSEC + URL_REGISTER_JWKS,

}

// Register Endpoints (Auth)
export const registerEndpointsAuth = {
    
    // Discovery Endpoints
    DATA_HOLDER_BRANDS: BASE_URL_REGISTER_DISCOVERY + URL_REGISTER_DATA_HOLDER_BRANDS,

}
